config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  post 'top/login'
  root 'top#main'
  get 'top/logout'
  get 'top/new'
  post 'top/create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def L4
        session[:c] || 0
        session[:c] = session[:c].to_i + 1
        render plain: session[:c]
    end
end

app/controllers/top_controller.rb
require 'bcrypt'

class TopController < ApplicationController
    def main
        if session[:login_uid]!=nil
            render "main"
        else
            render "login"
        end
    end
    
    def login
        
        user = User.find_by(uid: params[:uid])
        
        if user
            
            if  BCrypt::Password.new(user.pass) == params[:pass]
                session[:login_uid]=params[:uid]
                redirect_to top_main_path
            else
                render "error"
            end
        else
            render "error"
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to top_main_path
    end
    
    #def new
        #render "create"
    #end
    
    def create
        hashed_password = BCrypt::Password.create(params[:pass])
        user = User.new(uid: params[:uid], pass: hashed_password)
        user.save
        redirect_to top_main_path  #"/"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CS3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
<h1>エラーです</h1>

<%= link_to '戻る', :back %>

app/views/top/login.html.erb
<%= form_tag '/top/login', method: :post, data:{turbo:false} do %>
    <%= label_tag :uid, 'ユーザーID' %>
    <%= text_field_tag :uid %>
    <%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %>
    <%= submit_tag 'ログイン' %>
<% end %>

<p><%= link_to '新規登録はこちら', top_new_path %></p>

app/views/top/main.html.erb
<h1>ログイン中だお</h1>

<%= link_to 'ログアウト', top_logout_path %>

app/views/top/new.html.erb
<%= form_tag ({ action: :create }) do %>
  <%= label_tag :uid, 'ユーザー名' %>
  <%= text_field_tag :uid %>
  <%= label_tag :pass, 'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag '新規登録' %>
<% end %>